#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir m2/repository                
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_73 ]
        then
                cd $OPENSHIFT_DATA_DIR
		wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u73-b02/jdk-8u73-linux-x64.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.3 ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
fi


cd $OPENSHIFT_REPO_DIR
export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin
export MAVEN_OPTS="-Xms384m -Xmx412m"
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_73
export PATH=$JAVA_HOME/bin:$M2:$PATH

mvn -s settings.xml clean install
