#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_73
export TOMCAT_HOME=$OPENSHIFT_DATA_DIR/apache-tomcat-8.0.32
export PATH=$JAVA_HOME/bin:$PATH

cd $TOMCAT_HOME/bin
./startup.sh
